### ISSUE TITLE
Character API

### ISSUE THREAD

**Issue by ScottKane** [nxrighthere/UnrealCLR#26]
Any idea when `Pawn.SetupPlayerInputComponent()` is likely to be implemented? This along with `Character.Jump()` and `Character.StopJumping()` will be pretty important to getting some actual gameplay going through the plugin

**Comment by nxrighthere** [comment]
Don't hesitate to tell what API you need so I can expose it with a higher priority.

**Comment by ScottKane** [comment]
It's hard to give a priority list for setting up a basic character as you need to touch so many API's. From the research I've done into the C++ implementation the main things needed are (in no particular order):

Pawn.SetupPlayerInputComponent()
Pawn.Controller (Controller will need a minimum of vars/functions for ControlRotation)
Pawn.AddMovementInput()
Pawn.AddControllerYawInput()
Pawn.AddControllerPitchInput()
RotationMatrix
Axis

The following class is an example of how I imagine this would come together:

```C#
public class PlayerCharacter : Character
{
    private readonly SpringArmComponent _springArmComponent;
    private readonly CameraComponent _cameraComponent;

    public PlayerCharacter() : base(nameof(PlayerCharacter))
    {
        _springArmComponent = CreateDefaultSubObject<SpringArmComponent>(nameof(SpringArmComponent));
        _springArmComponent.SetupAttachment(RootComponent);

        _cameraComponent = CreateDefaultSubObject<CameraComponent>(nameof(CameraComponent));
        _cameraComponent.SetupAttachment(_springArmComponent);
    }

    public static void MoveForward(float value)
    {
        var direction = new RotationMatrix(Controller.GetControlRotation()).GetScaledAxis(Axis.X);
        AddMovementInput(direction, value);
    }

    private static void MoveRight(float value)
    {
        var direction = new RotationMatrix(Controller.GetControlRotation()).GetScaledAxis(Axis.Y);
        AddMovementInput(direction, value);
    }

    private static void TurnRate(float value) => AddControllerYawInput(value * 45.0f * World.DeltaTime);

    private static void LookRate(float value) => AddControllerPitchInput(value * 45.0f * World.DeltaTime);

    public virtual override void SetupPlayerInputComponent(InputComponent inputComponent)
    {
        base.SetupPlayerInputComponent(inputComponent);

        inputComponent.BindAction("Jump", InputEvent.Pressed, Jump);
        inputComponent.BindAction("Jump", InputEvent.Released, StopJumping);

        inputComponent.BindAxis("MoveForward", MoveForward);
        inputComponent.BindAxis("MoveRight", MoveRight);

        inputComponent.BindAxis("Turn", AddControllerYawInput);
        inputComponent.BindAxis("Look", AddControllerPitchInput);

        inputComponent.BindAxis("TurnRate", TurnRate);
        inputComponent.BindAxis("LookRate", LookRate);
    }
}
```

**Comment by nxrighthere** [comment]
`APawn::SetupPlayerInputComponent()` is a protected function, you will need to use `Pawn.GetPlayerController()` to setup the input component after the next commit.

`APawn::AddMovementInput()` takes `FVector` as an input, you don't assign `FRotationMatrix` directly there.

`FRotationMatrix` will not be re-implemented in C# for now, use vectors and quaternion functionality from `System.Numerics` instead.

**Comment by nxrighthere** [comment]
And in case if you will need more math functionality, see [this](https://github.com/nxrighthere/UnrealCLR/blob/master/API/Maths.md) class.

**Comment by ScottKane** [comment]
Ahh ok, I had seen that FRotationMatrix(Controller->GetControlRotation()).GetScaledAxis(EAxis::X) returns a Vector

**Comment by nxrighthere** [comment]
Those custom abstractions are not doing anything special under the hood (see [FMatrix::GetScaledAxis()](https://github.com/EpicGames/UnrealEngine/blob/8acb4df6c2ee9e6666dec3476af15636d246eab5/Engine/Source/Runtime/Core/Public/Math/Matrix.inl#L530)). Not worth wasting energy on that for now.

**Comment by ScottKane** [comment]
Ok thanks for the link

**Comment by ScottKane** [comment]
I think once we can get this functionality of the Character working, it will be easy to recreate some of the existing UE4 samples (first person/third person) with UnrealCLR which will probably help to get people on board

**Comment by nxrighthere** [comment]
Yea, absolutely, I'm working on this API at the moment.

**Comment by ScottKane** [comment]
Awesome, I'm not the strongest C++ dev but can get by with it so if I have an idea of how the API's are linking up I can try and help with expanding the Framework coverage

**Comment by nxrighthere** [comment]
`Controller.GetControlRotation()` will return a quaternion instead, so that should be okay, I think.

**Comment by nxrighthere** [comment]
In general, if you see `FRotator` somewhere in Unreal's functionality, here it becomes a quaternion.

**Comment by ScottKane** [comment]
Ok so general rule FRotator = Quaternion and FVector = Vector3

**Comment by ScottKane** [comment]
@nxrighthere Would it be possible to add a version of BindAction/BindAxis that takes an object reference to allow us to bind non static methods as it makes things like this a bit awkward:

```C#
input.BindAxis("MoveForward", Move);
```

```C#
public static void Move(float value) => base.AddMovementInput(Controller.GetControlRotation(), value); // Can't be done and not fun if you have a constructed object
```

But if we could do:

```C#
input.BindAxis("MoveForward", this, Move);
```

```C#
public void Move(float value) => base.AddMovementInput(Controller.GetControlRotation(), value);
```

**Comment by nxrighthere** [comment]
With the current version of the language, as far as I know, it's not possible to obtain a pointer to an instantiated method and safely rely on it because of GC.

**Comment by ScottKane** [comment]
What if the class implements IDisposable with the GC turned off? That way we can ensure that the pointer method exists and maybe as part of the Framework provide a method to call on Dispose() to remove the pointer?

```C#
public void Dispose()
{
    Engine.RemovePointer(this, MethodName);
}
```

Maybe something along the lines of this?

**Comment by nxrighthere** [comment]
The problem is that GC is moving and reclaiming the memory, so only delegates can be used as an intermediate callback, but that means storing references somewhere internally. If the registered callback was released natively, it means a reference will persist on the managed side, in other words, a memory leak.

**Comment by nxrighthere** [comment]
It's probably will be possible to solve this with C# 9.0 and unsafe code, but I'm not sure.

**Comment by nxrighthere** [comment]
I deal with a lot of language and runtime limitations because .NET Core is not designed for embedding to game engines like Lua, for example. So I have to use workarounds like that to make things done.

**Comment by ScottKane** [comment]
Ok so I will just have to assign a static instance on object construction to use instead. I have had a look through the C# 9 features but admittedly haven't looked much into the runtime stuff. Mainly liked the look of records and when/not keywords.

**Comment by nxrighthere** [comment]
C# 9.0 function pointers is what might solve this.

**Comment by ScottKane** [comment]
Looks to be implemented in Roslyn: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACBmAAgFcA7KCAMzgJwEYA2GgJhtoHYBYAKAG9uCBrRgBM4GOAHMI8AFQAeNCRgA+AgAcA9ovgICAXgIAyALIRFAbn6CrA/EILaCpxQAoAlAT5dBPmmwIADJbeggC+3KFAA===

**Comment by nxrighthere** [comment]
Yes, it was merged into the master not so long time ago.

**Comment by ScottKane** [comment]
@nxrighthere I think all I need to be able to test what I have so far is `CreateDefaultSubObject<T>()` (should this live on Actor in the C# implementation?) and `Controller.GetControlRotation()`

**Comment by nxrighthere** [comment]
What are you trying to achieve with `CreateDefaultSubObject<T>()`? To create components attached to a particular actor, you use constructors of component classes here, it's the same thing essentially.

**Comment by ScottKane** [comment]
Ahh ok I did think of that, just wasn't sure that it would be parented correctly in the editor. The constructor will work fine. Then I guess I just need `Controller.GetControlRotation()` to test `AddMovementInput()` with input events

**Comment by ScottKane** [comment]
Also `SpringArmComponent` to go with `CameraComponent` and I think that is everything needed to get a character playable

**Comment by nxrighthere** [comment]
I'll expose it right after the character API.

**Comment by ScottKane** [comment]
Awesome thanks

**Comment by ScottKane** [comment]
Also just wondering about SceneComponent, should it have another constructor to allow it to be attached to another SceneComponent instead of just Actor?

**Comment by nxrighthere** [comment]
Use `SceneComponent.AttachToComponent()` for that.

**Comment by ScottKane** [comment]
Ahh ok thanks, hadn't noticed that

**Comment by nxrighthere** [comment]
Basic functionality is exposed but not tested. Everything else that we discussed is on the way.

**Comment by ScottKane** [comment]
Ok cool thanks, will give it a go now

**Comment by ScottKane** [comment]
Am I stupid? What is happening here:

```C#
public class Player : Character
{
    public Player() : base($"{nameof(Player) + (Game.GetPlayerCount() + 1)}")
    {
        // An object reference is required for the non-static field, method, or property 'Controller.GetControlRotation()'
        var rotation = Controller.GetControlRotation();
    }
}
```

Shouldn't this be static?

**Comment by ScottKane** [comment]
Oh nevermind, it's on the PlayerController

**Comment by nxrighthere** [comment]
`Controller` is an abstract class, you work with `AIController` or `PlayerController` classes that can be obtained with `Pawn.GetAIController()` and `Pawn.GetPlayerController()` respectively as was mentioned [before](https://github.com/nxrighthere/UnrealCLR/issues/26#issuecomment-675444842).

**Comment by ScottKane** [comment]
Yeah I noticed it was an abstract class straight after asking, think I have everything hooked up apart from the springarm. But then it should be good to test

**Comment by nxrighthere** [comment]
@ScottKane  [`SpringArmComponent`](https://github.com/nxrighthere/UnrealCLR/blob/master/API/SpringArmComponent.md) is exposed in https://github.com/nxrighthere/UnrealCLR/commit/ff1eff18f69d7d3410c8b44cff3817adb21a721d. This functionality is not tested.

**Comment by ScottKane** [comment]
@nxrighthere There's no public constructor on the SpringArmComponent yet

**Comment by nxrighthere** [comment]
Fixed now.

**Comment by ScottKane** [comment]
Ok so I'm getting errors while trying to create a character but an Actor works fine with the following example:

```C#
public static class Main
{
    public static void OnWorldBegin() => new Player();
}
```

Player using Actor (which works):

```C#
public class Player : Actor
{
    public Player() => Debug.AddOnScreenMessage(-1, 10.0f, Color.Aqua, "Works!");
}
```

Player using Character (which doesn't work):

```C#
public class Player : Character
{
    public Player() => Debug.AddOnScreenMessage(-1, 10.0f, Color.Aqua, "Doesn't!");
}
```

Causes the following in the output log:

```
LogSpawn: Warning: SpawnActor failed because of collision at the spawn location [X=0.000 Y=0.000 Z=0.000] for [Character]
LogUnrealCLR: Error: UnrealCLR::Module::Exception: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at UnrealEngine.Framework.Actor.set_Pointer(IntPtr value) in C:\Users\scott\Desktop\UnrealCLR\Source\Managed\Framework\Framework.cs:line 3787
   at Tests.Player..ctor() in D:\Repos\Unreal\4.25\Tests\Source\Tests\Tests\Tests.cs:line 105
   at Tests.Main.OnWorldBegin() in D:\Repos\Unreal\4.25\Tests\Source\Tests\Tests\Tests.cs:line 19
   at Invoke(IntPtr , Argument )
   at UnrealEngine.Runtime.Core.ExecuteManagedFunction(IntPtr managedFunction, Argument value)
```

**Comment by nxrighthere** [comment]
The actor has no collisions in this case, the engine error indicates a problem with that, make sure that a character doesn't collide with anything including the ground.

**Comment by ScottKane** [comment]
Ok but I've not set a transform for either the actor or the character when creating them so why is this error only happening for character? When they are both created at 0,0,0

**Comment by nxrighthere** [comment]
Because unlike an actor, a character represents a mesh with collision. Also, most likely you are using a default game mode instead of a custom one, which spawns a default pawn that might cause collisions as well.

**Comment by ScottKane** [comment]
Ok yeah you're right, just delete all the default crap in the scene. How are we supposed to set the starting Transform on the Actor/Pawn/Character. Probably don't always want things at 0,0,0

**Comment by ScottKane** [comment]
Oh nevermind, there's TeleportTo() assuming that calling it in the constructor will stop the error if there's something at 0,0,0 as long as the position you're TP'ing to is "safe"

**Comment by nxrighthere** [comment]
Yes, it should be moved within the same frame.

**Comment by nxrighthere** [comment]
There's a player start actor available for that, and you also can tweak the game mode.

**Comment by nxrighthere** [comment]
> Would it be possible to add a version of BindAction/BindAxis that takes an object reference to allow us to bind non static methods

@ScottKane Let's try this with https://github.com/nxrighthere/UnrealCLR/commit/3df87d8aaee0b5c2f28a7ed671d77a420c027eb6.

**Comment by ScottKane** [comment]
Ok I will give it a try

**Comment by ScottKane** [comment]
Just tried both with non static methods and they are working

**Comment by ScottKane** [comment]
@nxrighthere The following is throwing a null reference on `BindPlayerInput(InputComponent);`:

```C#
public class Player : Character
{
    private readonly PlayerController _controller;

    public Player() : base(nameof(Player))
    {
        _controller = World.GetFirstPlayerController();
        SetEnableInput(_controller, true);

        new StaticMeshComponent(this).SetStaticMesh(StaticMesh.Cube);
        var springArmComponent = new SpringArmComponent(this);
        new CameraComponent(this).AttachToComponent(springArmComponent, AttachmentTransformRule.KeepRelativeTransform);

        BindPlayerInput(InputComponent);
    }

    public void Move(float value)
    {
        var rotation = _controller.GetControlRotation();
        var direction = new Vector3 { X = rotation.X, Y = rotation.Y, Z = rotation.Z };
        AddMovementInput(direction, value);
    }

    private void LookHorizontal(float value) => AddControllerYawInput(value);
    private void LookVertical(float value) => AddControllerPitchInput(value);

    public void BindPlayerInput(InputComponent input)
    {
        input.BindAction("Jump", InputEvent.Pressed, Jump);
        input.BindAction("Jump", InputEvent.Released, StopJumping);

        input.BindAxis("MoveForward", Move);
        input.BindAxis("MoveRight", Move);

        input.BindAxis("LookHorizontal", LookHorizontal);
        input.BindAxis("LookVertical", LookVertical);
    }
}
```

Shouldn't `SetEnableInput(_controller, true);` be giving `InputComponent` a value?

**Comment by ScottKane** [comment]
Ok so the following is logging the correct information but isn't actually moving or looking

```C#
public class Player : Character
{
    private readonly PlayerController _controller;

    public Player() : base(nameof(Player))
    {
        _controller = World.GetFirstPlayerController();

        new StaticMeshComponent(this).SetStaticMesh(StaticMesh.Cube);
        var springArmComponent = new SpringArmComponent(this);
        new CameraComponent(this).AttachToComponent(springArmComponent, AttachmentTransformRule.KeepRelativeTransform);

        BindPlayerInput(_controller.InputComponent);
    }

    public void Move(float value)
    {
        if (Math.Abs(value) > 0) Debug.AddOnScreenMessage(-1, 0.1f, Color.LimeGreen, $"Moving {value}");
        var rotation = _controller.GetControlRotation();
        var direction = new Vector3 { X = rotation.X, Y = rotation.Y, Z = rotation.Z };
        AddMovementInput(direction, value);
    }

    public void Horizontal(float value)
    {
        if (Math.Abs(value) > 0) Debug.AddOnScreenMessage(-1, 0.1f, Color.LimeGreen, $"Looking Horizontal {value}");
        AddControllerYawInput(value);
    }

    public void Vertical(float value)
    {
        if (Math.Abs(value) > 0) Debug.AddOnScreenMessage(-1, 0.1f, Color.LimeGreen, $"Looking Vertical {value}");
        AddControllerPitchInput(value);
    }

    public void BindPlayerInput(InputComponent input)
    {
        input.BindAction("Jump", InputEvent.Pressed, Jump);
        input.BindAction("Jump", InputEvent.Released, StopJumping);

        input.BindAxis("MoveForward", Move);
        input.BindAxis("MoveRight", Move);

        input.BindAxis("Horizontal", Horizontal);
        input.BindAxis("Vertical", Vertical);
    }
}
```

This still doesn't allow the character to move. It's like the controller isn't accepting the input

**Comment by nxrighthere** [comment]
`Actor.SetEnableInput()` is intended for non-pawn actors, pawns should be possessed with `AController::Possess()`, but it's not exposed. I'll expose it and update the documentation.

> Shouldn't SetEnableInput(_controller, true); be giving InputComponent a value?

Nope, [`AActor::EnableInput()`](https://github.com/EpicGames/UnrealEngine/blob/f73bee2c1cc1e4ececc7ebf0eeb3af1661de9ae0/Engine/Source/Runtime/Engine/Private/Actor.cpp#L3621) allocates/registers `UInputComponent`, and then pushes it to the stack of input handled by a `APlayerController`.

**Comment by ScottKane** [comment]
Ok so this means on the character although it is receiving the input events, it won't move until it is possessed?

**Comment by ScottKane** [comment]
Also should there be a `PlayerInput` equivalent of `Engine.AddActionMapping()` so that you can add bindings per character or is there another way to do this?

**Comment by nxrighthere** [comment]
> Ok so this means on the character although it is receiving the input events, it won't move until it is possessed?

Yes, it can't be controlled in this case since `PlayerController` does not possess the pawn, I need to expose more functionality for that (working on it).

**Comment by ScottKane** [comment]
> `InputComponent.BindAction()` should be used for this, including this case.

OK so only one set of mappings, multiple bindings

**Comment by nxrighthere** [comment]
Done in https://github.com/nxrighthere/UnrealCLR/commit/d49df87d5fcf5de0ee718b4a742d036505fc401b. Try to set `this.AutoPossessPlayer = AutoReceiveInput.Player0;` at construction now.

**Comment by nxrighthere** [comment]
I refactored it to properties in https://github.com/nxrighthere/UnrealCLR/commit/537f04164387f26d45ccea65a683f4d9d480e3a7.

**Comment by ScottKane** [comment]
Added the property assignment to my constructor but I'm still not getting any movement

**Comment by nxrighthere** [comment]
I don't see action and axis mapping in your code, is that set correctly?

**Comment by nxrighthere** [comment]
> Also should there be a PlayerInput equivalent of Engine.AddActionMapping() so that you can add bindings per character or is there another way to do this?

Actually, mapping functions are [available](https://github.com/nxrighthere/UnrealCLR/blob/master/API/PlayerInput.md) there.

**Comment by ScottKane** [comment]
I was binding the input in Main but here's what I'm using now for testing:

```C#
public static class Main
{
    public static void OnWorldBegin() => new Player();
}

public class Player : Character
{
    private readonly PlayerController _controller;

    public Player() : base(nameof(Player))
    {
        _controller = World.GetFirstPlayerController();
        AutoPossessPlayer = AutoReceiveInput.Player0;

        new StaticMeshComponent(this).SetStaticMesh(StaticMesh.Cube);
        var springArmComponent = new SpringArmComponent(this);
        new CameraComponent(this).AttachToComponent(springArmComponent, AttachmentTransformRule.KeepRelativeTransform);

        MapPlayerInput(_controller.GetPlayerInput());
        BindPlayerInput(_controller.InputComponent);
    }

    public void Move(float value)
    {
        if (Math.Abs(value) > 0) Debug.AddOnScreenMessage(-1, 0.1f, Color.LimeGreen, $"Moving {value}");
        var rotation = _controller.GetControlRotation();
        var direction = new Vector3 { X = rotation.X, Y = rotation.Y, Z = rotation.Z };
        AddMovementInput(direction, value);
    }

    public void Horizontal(float value)
    {
        if (Math.Abs(value) > 0) Debug.AddOnScreenMessage(-1, 0.1f, Color.LimeGreen, $"Looking Horizontal {value}");
        AddControllerYawInput(value);
    }

    public void Vertical(float value)
    {
        if (Math.Abs(value) > 0) Debug.AddOnScreenMessage(-1, 0.1f, Color.LimeGreen, $"Looking Vertical {value}");
        AddControllerPitchInput(value);
    }

    public void MapPlayerInput(PlayerInput input)
    {
        input.AddActionMapping("Jump", Keys.SpaceBar);

        input.AddAxisMapping("MoveForward", Keys.W);
        input.AddAxisMapping("MoveForward", Keys.S, -1f);

        input.AddAxisMapping("MoveRight", Keys.D);
        input.AddAxisMapping("MoveRight", Keys.A, -1f);

        input.AddAxisMapping("Horizontal", Keys.MouseX);
        input.AddAxisMapping("Vertical", Keys.MouseY);
    }

    public void BindPlayerInput(InputComponent input)
    {
        input.BindAction("Jump", InputEvent.Pressed, Jump);
        input.BindAction("Jump", InputEvent.Released, StopJumping);

        input.BindAxis("MoveForward", Move);
        input.BindAxis("MoveRight", Move);

        input.BindAxis("Horizontal", Horizontal);
        input.BindAxis("Vertical", Vertical);
    }
}
```

This currently is logging messages as expected but not actually moving the character as expected.

**Comment by nxrighthere** [comment]
It seems that only `APawn::SetupPlayerInputComponent()` should be used to set up input properly, but since it's protected and can be used only in a constructor of a derived class in C++, I need to think how to expose it in C#.

**Comment by nxrighthere** [comment]
@ScottKane Anything changes if you set `_controller.Possess(this);` with or without `AutoPossessPlayer = AutoReceiveInput.Player0;`?

**Comment by ScottKane** [comment]
@nxrighthere The code isn't quite functioning as intended so I will have to figure that out but I can now control the character by using `_controller.Possess(this);` without `AutoPossessPlayer = AutoReceiveInput.Player0;`

**Comment by nxrighthere** [comment]
Yes, at this point, you will need [`CharacterMovementComponent`](https://docs.unrealengine.com/en-US/API/Runtime/Engine/GameFramework/UCharacterMovementComponent/index.html), which is a beast of movement components...

**Comment by riddlemd** [comment]
@ScottKane how did you get Player class working? World.GetFirstPlayerController() is always returning null for me.
